import {cables,devices,required,match,online} from './engine.js';
const $=s=>document.querySelector(s);let connected=[],selected='ethernet',start=null,mistakes=0,hints=0,celebrated=false;
try{const save=JSON.parse(localStorage.getItem('network-lab-v1'));if(save&&Array.isArray(save.connected)){connected=[...new Set(save.connected.filter(i=>Number.isInteger(i)&&i>=0&&i<required.length))];mistakes=Number(save.mistakes)||0;hints=Number(save.hints)||0;}}catch{}
function save(){try{localStorage.setItem('network-lab-v1',JSON.stringify({connected,mistakes,hints}));}catch{}}
function message(text,error=false){$('#feedback').textContent=text;$('#feedback').classList.toggle('error',error);}
function inspect(name,info){$('#inspect-name').textContent=name;$('#inspect-info').textContent=info;}
function draw(){const svg=$('#wires'),rect=$('#scene').getBoundingClientRect();svg.replaceChildren();for(const i of connected){const r=required[i],a=$(`[data-key="${r.a}:${r.ap}"]`).getBoundingClientRect(),b=$(`[data-key="${r.b}:${r.bp}"]`).getBoundingClientRect();const x=a.x+a.width/2-rect.x,y=a.y+a.height/2-rect.y,xx=b.x+b.width/2-rect.x,yy=b.y+b.height/2-rect.y;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M${x},${y} C${x},${(y+yy)/2+25} ${xx},${(y+yy)/2+25} ${xx},${yy}`);p.setAttribute('stroke',cables.find(c=>c.id===r.cable).color);p.setAttribute('stroke-width','3');p.setAttribute('fill','none');p.setAttribute('opacity','.75');if(r.cable==='wifi')p.setAttribute('stroke-dasharray','5 7');svg.append(p);}}
function render(){const live=online(connected);$('#devices').innerHTML=devices.map(d=>`<article class="device ${live.has(d.id)?'online':''}" style="left:${d.x}%;top:${d.y}%"><div class="device-top"><span class="device-icon">${d.icon}</span><span class="status">${live.has(d.id)?'● ONLINE':'○ OFFLINE'}</span></div><button class="device-name" data-inspect="${d.id}">${d.name}</button><div class="ports">${d.ports.map(p=>`<button class="port ${start?.device===d.id&&start?.port===p?'selected':''} ${connected.some(i=>{const r=required[i];return(r.a===d.id&&r.ap===p)||(r.b===d.id&&r.bp===p);})?'connected':''}" data-device="${d.id}" data-port="${p}" data-key="${d.id}:${p}" aria-label="${d.name} ${p} port" aria-pressed="${start?.device===d.id&&start?.port===p}">${p==='power'?'PWR':p.toUpperCase()}</button>`).join('')}</div></article>`).join('');$('#cables').innerHTML=cables.map(c=>`<button class="cable ${selected===c.id?'active':''}" data-cable="${c.id}" aria-pressed="${selected===c.id}"><svg viewBox="0 0 80 50" aria-hidden="true"><ellipse cx="40" cy="23" rx="28" ry="17" fill="none" stroke="${c.color}" stroke-width="5"/><ellipse cx="40" cy="23" rx="21" ry="12" fill="none" stroke="${c.color}" stroke-width="3"/><path d="M15 32L9 43M64 32L71 43" stroke="${c.color}" stroke-width="5"/><path d="M6 40L13 45M67 45L75 40" stroke="#c9d4e2" stroke-width="6"/></svg>${c.name}<small>${c.id==='wifi'?'WIRELESS':c.id==='hdmi'?'VIDEO':'CONNECTION'}</small></button>`).join('');const endpoints=['router','switch','ap','pc','phone','camera','printer','laptop'],n=endpoints.filter(id=>live.has(id)).length;$('#count').textContent=`${connected.length} / ${required.length}`;$('#progress').value=connected.length;$('#online').textContent=`${n} / 8 office devices online`;$('#goal-uplink').classList.toggle('done',live.has('switch'));$('#goal-power').classList.toggle('done',required.every((r,i)=>r.cable!=='power'||connected.includes(i)));$('#goal-online').classList.toggle('done',n===8);$('#undo').disabled=!connected.length;save();requestAnimationFrame(draw);if(connected.length===required.length&&!celebrated){celebrated=true;$('#result').textContent=`14 correct connections · ${mistakes} incorrect attempts · ${hints} hints used`;$('#complete').showModal();}}
$('#devices').addEventListener('click',e=>{const inspectButton=e.target.closest('[data-inspect]');if(inspectButton){const d=devices.find(d=>d.id===inspectButton.dataset.inspect);inspect(d.name,d.info);return;}const b=e.target.closest('[data-port]');if(!b)return;const end={device:b.dataset.device,port:b.dataset.port};if(!start){start=end;message('Source selected. Click a destination port, or click the source again to cancel.');}else if(start.device===end.device&&start.port===end.port){start=null;message('Selection cleared. Choose a source port.');}else{const i=match(start,end,selected);start=null;if(i<0){mistakes++;message('That connection does not fit this network. Check the cable type and port labels, or inspect a device.',true);}else if(connected.includes(i)){message('That link is already connected.',true);}else{connected.push(i);message(required[i].lesson);}}render();});
$('#cables').addEventListener('click',e=>{const b=e.target.closest('[data-cable]');if(!b)return;selected=b.dataset.cable;start=null;const c=cables.find(c=>c.id===selected);inspect(c.name,c.description);message(`${c.name} selected. Choose two matching ports.`);render();});
$('#hint').onclick=()=>{const i=required.findIndex((r,i)=>!connected.includes(i));if(i<0){message('Everything is connected. Mission complete!');return;}hints++;const r=required[i];message(`Hint: use ${cables.find(c=>c.id===r.cable).name} from ${devices.find(d=>d.id===r.a).name} (${r.ap.toUpperCase()}) to ${devices.find(d=>d.id===r.b).name} (${r.bp.toUpperCase()}).`);save();};
$('#undo').onclick=()=>{connected.pop();start=null;celebrated=false;message('Last connection removed.');render();};$('#reset').onclick=()=>{connected=[];start=null;mistakes=0;hints=0;celebrated=false;message('New attempt started. Select a cable and connect two ports.');render();};$('#continue').onclick=()=>$('#complete').close();window.addEventListener('resize',draw);document.addEventListener('keydown',e=>{if(e.key==='Escape'){start=null;render();}});render();
