import { required, linkIndex } from './engine.js';
// Missions name the office's required links by id (see engine.js), e.g. 'switch-pc' or 'ups-router'.
// `start` links are already plugged in, `add` links are the player's job, and `faults` are
// wrong cables already in the scene that must be unplugged.
const isPatch = r => r.a === 'patch' || r.b === 'patch';
// The direct-wired office (chapters 1-4) and its structured-cabling version (chapter 5).
const ALL = required.filter(r => !isPatch(r)).map(r => r.id);
const RUNS = ['patch-camera', 'patch-pc', 'patch-ap', 'patch-printer', 'patch-phone'];
const CORDS = ['switch-j1', 'switch-j2', 'switch-j3', 'switch-j4', 'switch-j5'];
// Everything a fully patched office needs: the closet, wall runs, patch cords, power and Wi-Fi.
const PATCHED = ALL.filter(id => !id.startsWith('switch-')).concat(RUNS, CORDS);
const patchedExcept = (...skip) => PATCHED.filter(id => !skip.includes(id));
const CLOSET = [
  'isp-modem',
  'modem-router',
  'router-switch',
  'ups-modem',
  'ups-router',
  'ups-switch',
];
const except = (...skip) => ALL.filter(id => !skip.includes(id));
const fault = (a, ap, b, bp, cable, why) => ({ a, ap, b, bp, cable, why });
// Link ids are resolved to indices into `required`, which is what game state stores.
const mission = (id, track, title, brief, start, add, faults = []) => ({
  id,
  track,
  title,
  brief,
  start: start.map(linkIndex),
  add: add.map(linkIndex),
  faults,
});
export const tracks = ['Installs', 'Builds', 'Outages', 'Troubleshooting', 'Patch panel'];
export const missions = [
  mission(
    'fiber',
    'Installs',
    'Light up the fiber',
    'The ISP just installed fiber. Connect the modem/ONT to the optical handoff and give it backup power.',
    [],
    ['isp-modem', 'ups-modem'],
  ),
  mission(
    'edge',
    'Installs',
    'Router on the edge',
    'The modem has signal. Put the router behind it and power it from the UPS.',
    ['isp-modem', 'ups-modem'],
    ['modem-router', 'ups-router'],
  ),
  mission(
    'core',
    'Installs',
    'Core switch install',
    'Rack the PoE switch: feed it from the router LAN and give it UPS power.',
    ['isp-modem', 'modem-router', 'ups-modem', 'ups-router'],
    ['router-switch', 'ups-switch'],
  ),
  mission(
    'workstation',
    'Installs',
    'First workstation',
    'A new hire starts today. Get their desktop PC on the wired network with backup power.',
    CLOSET,
    ['switch-pc', 'ups-pc'],
  ),
  mission(
    'printer',
    'Installs',
    'Network printer setup',
    'Finance needs to print invoices. Wire the network printer and power it.',
    CLOSET,
    ['switch-printer', 'ups-printer'],
  ),
  mission(
    'voip',
    'Installs',
    'VoIP phone rollout',
    'Replace the old analog line: connect the VoIP phone. PoE powers it, so no power cable is needed.',
    CLOSET,
    ['switch-phone'],
  ),
  mission(
    'camera',
    'Installs',
    'Security camera install',
    'Facilities wants the entrance covered. Connect the PoE IP camera.',
    CLOSET,
    ['switch-camera'],
  ),
  mission(
    'wireless',
    'Installs',
    'Wireless coverage',
    'Visitors need Wi-Fi. Mount the access point and uplink it to the PoE switch.',
    CLOSET,
    ['switch-ap'],
  ),
  mission(
    'laptop',
    'Installs',
    'Laptop onboarding',
    "The access point is live. Join the manager's laptop to the office Wi-Fi.",
    [...CLOSET, 'switch-ap'],
    ['ap-laptop'],
  ),
  mission(
    'poe',
    'Installs',
    'PoE rollout',
    'Bring up every PoE device at once: access point, VoIP phone, and IP camera.',
    CLOSET,
    ['switch-ap', 'switch-phone', 'switch-camera'],
  ),
  mission(
    'closet',
    'Builds',
    'Build the comms closet',
    'An empty rack. Build the internet uplink (ISP, modem, router, switch) and put all of it on the UPS.',
    [],
    CLOSET,
  ),
  mission(
    'desks',
    'Builds',
    'Wired desks',
    'Wireless and PoE are done. Finish the wired desks: desktop and printer, with UPS power.',
    [...CLOSET, 'switch-ap', 'switch-phone', 'switch-camera', 'ap-laptop'],
    ['switch-pc', 'switch-printer', 'ups-pc', 'ups-printer'],
  ),
  mission(
    'endpoints',
    'Builds',
    'Furnish the office',
    'The closet is ready. Connect every endpoint in the office and get it online.',
    CLOSET,
    [
      'switch-ap',
      'switch-pc',
      'switch-phone',
      'switch-camera',
      'switch-printer',
      'ap-laptop',
      'ups-pc',
      'ups-printer',
    ],
  ),
  mission(
    'power',
    'Builds',
    'Backup power drill',
    'All the data cables are in, but nothing is on the UPS. Power every mains device.',
    [
      'isp-modem',
      'modem-router',
      'router-switch',
      'switch-ap',
      'switch-pc',
      'switch-phone',
      'switch-camera',
      'switch-printer',
      'ap-laptop',
    ],
    ['ups-modem', 'ups-router', 'ups-switch', 'ups-pc', 'ups-printer'],
  ),
  mission(
    'office',
    'Builds',
    'Connect the whole office',
    'The original challenge: wire the entire office from scratch.',
    [],
    ALL,
  ),
  mission(
    'dark',
    'Outages',
    'Half the office went dark',
    'After the cleaners came through, most of the office dropped offline. Find what was unplugged.',
    except('ups-switch'),
    ['ups-switch'],
  ),
  mission(
    'morning',
    'Outages',
    'Monday morning outage',
    'Nobody can reach the internet, yet the modem has signal. Work inward and find the missing link.',
    except('ups-router'),
    ['ups-router'],
  ),
  mission(
    'print-down',
    'Outages',
    'Printer offline',
    "The printer shows offline on everyone's screen. Get it back.",
    except('ups-printer'),
    ['ups-printer'],
  ),
  mission(
    'no-wifi',
    'Outages',
    'No Wi-Fi anywhere',
    "The laptop can't see the office network. Restore wireless.",
    except('switch-ap', 'ap-laptop'),
    ['switch-ap', 'ap-laptop'],
  ),
  mission(
    'isp-down',
    'Outages',
    'Internet is down',
    'After a power cut nothing reaches the internet. Restore the uplink from the ISP inward.',
    except('isp-modem', 'ups-modem'),
    ['isp-modem', 'ups-modem'],
  ),
  mission(
    'chaos',
    'Outages',
    'Cleaning crew chaos',
    'Several cables were knocked out overnight. Find and reconnect all of them.',
    except('router-switch', 'switch-camera', 'ups-pc'),
    ['router-switch', 'switch-camera', 'ups-pc'],
  ),
  mission(
    'wrong-side',
    'Troubleshooting',
    'Wrong side of the router',
    'Nobody has internet. The modem seems to be plugged into the wrong router port.',
    except('modem-router'),
    ['modem-router'],
    [
      fault(
        'modem',
        'eth',
        'router',
        'lan',
        'ethernet',
        'The modem must connect to the router WAN port. LAN faces the office.',
      ),
    ],
  ),
  mission(
    'backwards',
    'Troubleshooting',
    'Backwards uplink',
    'A contractor rewired the router and now the office is offline. Fix the WAN and LAN cabling.',
    except('modem-router', 'router-switch'),
    ['modem-router', 'router-switch'],
    [
      fault(
        'switch',
        'eth',
        'router',
        'wan',
        'ethernet',
        'The switch belongs on a router LAN port. WAN is for the modem.',
      ),
    ],
  ),
  mission(
    'dark-camera',
    'Troubleshooting',
    'The camera is dark',
    'The new camera never powers on. Check what it is plugged into.',
    except('switch-camera'),
    ['switch-camera'],
    [
      fault(
        'camera',
        'eth',
        'router',
        'lan',
        'ethernet',
        'The router LAN port does not supply PoE. The camera must connect to the PoE switch.',
      ),
    ],
  ),
  mission(
    'phone-cord',
    'Troubleshooting',
    'Phone cord mix-up',
    'The VoIP phone has no dial tone. Someone used the wrong kind of cable.',
    except('switch-phone'),
    ['switch-phone'],
    [
      fault(
        'switch',
        'eth',
        'phone',
        'eth',
        'phone',
        "An RJ11 phone cord can't carry Ethernet or PoE. Use a Cat6 cable.",
      ),
    ],
  ),
  mission(
    'bypass',
    'Troubleshooting',
    'Desktop bypassing the firewall',
    'Security flagged the desktop talking straight to the internet. Move it behind the router.',
    except('switch-pc'),
    ['switch-pc'],
    [
      fault(
        'pc',
        'eth',
        'modem',
        'eth',
        'ethernet',
        'Plugging a PC into the modem skips the router and its firewall.',
      ),
    ],
  ),
  mission(
    'ap-misplaced',
    'Troubleshooting',
    'Access point in the wrong place',
    "The access point lights never come on, so the laptop can't connect.",
    except('switch-ap'),
    ['switch-ap'],
    [
      fault(
        'ap',
        'eth',
        'router',
        'lan',
        'ethernet',
        'The access point needs PoE from the switch. The router LAN port has no power.',
      ),
    ],
  ),
  mission(
    'printer-cord',
    'Troubleshooting',
    'Printer cable swap',
    'The printer has power but no network. Inspect its cable.',
    except('switch-printer'),
    ['switch-printer'],
    [
      fault(
        'printer',
        'eth',
        'switch',
        'eth',
        'phone',
        'RJ11 phone cords fit loosely in Ethernet ports but carry no network traffic.',
      ),
    ],
  ),
  mission(
    'double',
    'Troubleshooting',
    'Double trouble',
    'Two tickets came in at once: no internet, and the camera is dark. Fix both.',
    except('modem-router', 'switch-camera'),
    ['modem-router', 'switch-camera'],
    [
      fault(
        'modem',
        'eth',
        'router',
        'lan',
        'ethernet',
        'The modem must connect to the router WAN port.',
      ),
      fault('camera', 'eth', 'router', 'lan', 'ethernet', 'The camera needs PoE from the switch.'),
    ],
  ),
  mission(
    'final',
    'Troubleshooting',
    'Final exam: the messy office',
    'You inherited a badly wired office. Remove every bad cable and rebuild it properly.',
    ['isp-modem', 'ap-laptop', 'ups-modem', 'ups-router', 'ups-pc', 'ups-printer'],
    [
      'modem-router',
      'router-switch',
      'switch-ap',
      'switch-pc',
      'switch-phone',
      'switch-camera',
      'switch-printer',
      'ups-switch',
    ],
    [
      fault(
        'modem',
        'eth',
        'router',
        'lan',
        'ethernet',
        'The modem must connect to the router WAN port.',
      ),
      fault(
        'ap',
        'eth',
        'router',
        'lan',
        'ethernet',
        'The access point needs PoE from the switch.',
      ),
      fault(
        'pc',
        'eth',
        'modem',
        'eth',
        'ethernet',
        'The desktop must sit behind the router, not on the modem.',
      ),
    ],
  ),
  mission(
    'first-jack',
    'Patch panel',
    'Patch the first jack',
    'This office uses structured cabling: every desk is cabled through the walls to a jack on the patch panel. Find the desktop PC’s jack and patch it to the switch.',
    patchedExcept(...CORDS, 'ap-laptop', 'ups-printer'),
    ['switch-j2'],
  ),
  mission(
    'patch-poe',
    'Patch panel',
    'Patch the PoE devices',
    'The camera, access point and phone are cabled to the panel but not patched. Patch their jacks to the PoE switch.',
    patchedExcept('switch-j1', 'switch-j3', 'switch-j4', 'switch-j5', 'ap-laptop', 'ups-printer'),
    ['switch-j1', 'switch-j3', 'switch-j5'],
  ),
  mission(
    'patch-floor',
    'Patch panel',
    'Patch the whole floor',
    'Move-in day. Patch every desk jack, power the printer, and get the laptop on Wi-Fi.',
    patchedExcept(...CORDS, 'ap-laptop', 'ups-printer'),
    [...CORDS, 'ap-laptop', 'ups-printer'],
  ),
  mission(
    'dead-jack',
    'Patch panel',
    'Dead jack',
    'The printer is offline, but someone swears they patched it. Check the panel labels.',
    patchedExcept('switch-j4'),
    ['switch-j4'],
    [
      fault(
        'switch',
        'eth',
        'patch',
        'j6',
        'ethernet',
        'J6 is a spare with nothing behind it. The printer is on J4.',
      ),
    ],
  ),
  mission(
    'rack-cord',
    'Patch panel',
    'Wrong cord in the rack',
    'The IP camera dropped off the network after a rack cleanup. Look closely at its patch cord.',
    patchedExcept('switch-j1'),
    ['switch-j1'],
    [
      fault(
        'switch',
        'eth',
        'patch',
        'j1',
        'phone',
        'An RJ11 phone cord does not carry Ethernet or PoE. Patch J1 with Ethernet.',
      ),
    ],
  ),
  mission(
    'new-drop',
    'Patch panel',
    'Terminate a new drop',
    'The access point moved, and its new cable run is not terminated yet. Connect the AP to its jack (J3), then patch J3 to the switch.',
    patchedExcept('patch-ap', 'switch-j3'),
    ['patch-ap', 'switch-j3'],
  ),
  mission(
    'structured',
    'Patch panel',
    'Structured cabling from scratch',
    'An empty office. Build the closet, run every desk to its labeled jack, patch the jacks, and power everything. Click Patch panel to read the jack labels.',
    [],
    PATCHED,
  ),
];
